service: auth-server


provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  timeout: 60 # optional, in seconds, default is 6
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    PROJECT_ID: ${file(config.json):PROJECT_ID}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}
  
functions:
  getAuthURL: #This function will build the authorization url with the provided information and return it
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
  getAccessToken: # this function will extract the access_token sent by the authorization server after authorization
    handler: handler.getAccessToken
    events: 
      - http:
          path: api/token/{code}
          method: get
  getCalendarEvents: # this function will take the access_token and request all events available - get
    handler: handler.getCalendarEvents
    events:
      - http:
          path: api/get-events/{access_token}
          method: get 
